name: Feature Branch CI

on:
  push:
    branches: ["feature/*"]

env:
  GO_VERSION: "1.24"

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Go workspace sync
        run: go work sync

      - name: Go vet
        run: go vet ./...

      - name: Build changed services
        run: |
          # Определяем какие сервисы изменились
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)

          if echo "$CHANGED_FILES" | grep -q "services/user-service"; then
            echo "Building user-service..."
            cd services/user-service && go build .
          fi

          if echo "$CHANGED_FILES" | grep -q "services/product-service"; then
            echo "Building product-service..."
            cd services/product-service && go build .
          fi

          if echo "$CHANGED_FILES" | grep -q "services/api-gateway"; then
            echo "Building api-gateway..."
            cd services/api-gateway && go build .
          fi

      - name: Notify Telegram
        if: always()
        run: |
          STATUS="${{ job.status == 'success' && 'SUCCESS' || 'FAILED' }}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="HTML" \
            -d text="$STATUS <b>Feature CI</b>%0A<b>Branch:</b> ${{ github.ref_name }}%0A<b>Author:</b> ${{ github.actor }}"
